name: Lint Java File

on:
  push:
    paths:
      - 'Calculator.java'
  workflow_dispatch:  # Allow manual trigger

jobs:
  lint:
    name: Super-Linter Java Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Super-Linter on Calculator.java
        uses: github/super-linter@v6
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVA: true
          FILTER_REGEX_INCLUDE: 'Calculator\.java'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
