name: Manual Java Lint

on:
  workflow_dispatch:  # Manual trigger via GitHub UI

jobs:
  lint-java:
    name: Run Super-Linter on Calculator.java
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Super-Linter - Scan Calculator.java
        uses: github/super-linter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVA: true
          FILTER_REGEX_INCLUDE: '^Calculator\.java$'
